-- DROP TABLE IF EXISTS EMPLOYEE;
-- DROP TABLE IF EXISTS ROLE;
-- DROP TABLE IF EXISTS POSITION;
-- DROP TABLE IF EXISTS DEPARTMENT;
-- DROP TABLE IF EXISTS USERS_ROLES;
-- CREATE TABLE IF NOT EXISTS EMPLOYEE(
--     ID BIGINT PRIMARY KEY AUTO_INCREMENT,
--     EMAIL VARCHAR(100) UNIQUE,
--
-- )
DROP DATABASE IF EXISTS capstone_test;
CREATE DATABASE IF EXISTS capstone_test;