DROP TABLE IF EXISTS NOTES;
DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(256) UNIQUE,
    PASSWORD VARCHAR(100),
    ENABLED  BOOLEAN DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    USERNAME VARCHAR(256),
    AUTHORITY VARCHAR(20),
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS NOTES
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(60),
    DESCRIPTION VARCHAR(256),
    OWNER       VARCHAR(256) NOT NULL,
    FOREIGN KEY (OWNER) REFERENCES USERS (USERNAME) ON DELETE CASCADE
);
